#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-09-11 11:52:01.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("read_file_paths() works", {

  expect_error(
    fakin.path.app:::read_file_paths()
    # could not find function "guess_file_metadata"
  )

})

