#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-09-11 11:52:06.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("inlineRadioButtons() works", {

  expect_error(
    fakin.path.app:::inlineRadioButtons()
    # Please specify a non-empty vector for `choices` (or, alternatively, for both `choiceNames` AND `choiceValues`).
  )

})

