#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-09-11 11:51:41.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("fileData() works", {

  expect_error(
    fakin.path.app:::fileData()
    # attempt to apply non-function
  )

})

