#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-09-11 11:51:49.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("plot_wordcloud_or_message() works", {

  expect_error(
    fakin.path.app:::plot_wordcloud_or_message()
    # argument "freq" is missing, with no default
  )

})

