#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-09-11 11:50:52.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("run_app_scan() works", {

  fakin.path.app:::run_app_scan()

})

