#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-09-11 11:51:22.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("run_in_fakin_database() works", {

  expect_error(
    fakin.path.app:::run_in_fakin_database()
    # argument "statement" is missing, with no default
  )

})

