#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-09-11 11:51:22.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("send_query_fetch_optionally() works", {

  expect_error(
    fakin.path.app:::send_query_fetch_optionally()
    # argument "con" is missing, with no default
  )

})

