#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-09-11 11:51:56.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("prepare_paths_for_network2() works", {

  expect_error(
    fakin.path.app:::prepare_paths_for_network2()
    # argument "paths" is missing, with no default
  )

})

