#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-09-11 11:52:06.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("remove_empty() works", {

  expect_error(
    fakin.path.app:::remove_empty()
    # argument "x" is missing, with no default
  )

})

