#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-09-11 11:51:52.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("plot_file_size_in_depth_gg() works", {

  expect_error(
    fakin.path.app:::plot_file_size_in_depth_gg()
    # argument "df" is missing, with no default
  )

})

