#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-09-11 11:51:59.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("prepare_for_n_level_treemap2() works", {

  expect_error(
    fakin.path.app:::prepare_for_n_level_treemap2()
    # argument "path_list" is missing, with no default
  )

})

