#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-09-11 11:52:06.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("read_slider_config_raw() works", {

  expect_error(
    fakin.path.app:::read_slider_config_raw()
    # argument "file" is missing, with no default
  )

})

